import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import L from"leaflet";import"leaflet/dist/leaflet.css";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
const services=[{id:"electricity",label:"Electricity",icon:"⚡"},{id:"water",label:"Water",icon:"💧"},{id:"internet",label:"Internet",icon:"🌐"},{id:"mobile",label:"Mobile",icon:"📱"}];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function App(){const[reports,setReports]=useState([]),[service,setService]=useState("all"),[map,setMap]=useState(null),[form,setForm]=useState({service:"electricity",description:""}),[loc,setLoc]=useState(null),[online,setOnline]=useState(true);const visible=useMemo(()=>service==="all"?reports:reports.filter(r=>r.service===service),[reports,service]);
useEffect(()=>{fetch(API+"/api/reports").then(r=>r.json()).then(setReports).catch(()=>setOnline(false));navigator.geolocation?.getCurrentPosition(p=>setLoc([p.coords.latitude,p.coords.longitude]));let ws;try{ws=new WebSocket(API.replace(/^http/,"ws")+"/ws");ws.onopen=()=>setOnline(true);ws.onclose=()=>setOnline(false);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==="snapshot")setReports(m.reports);if(m.type==="report.created")setReports(x=>[...x.filter(r=>r.id!==m.report.id),m.report]);if(m.type==="report.updated")setReports(x=>x.map(r=>r.id===m.report.id?m.report:r))}}catch{setOnline(false)}return()=>ws?.close()},[]);
useEffect(()=>{const m=L.map("map",{zoomControl:false}).setView([20.5937,78.9629],5);L.control.zoom({position:"bottomright"}).addTo(m);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(m);setMap(m);return()=>m.remove()},[]);
useEffect(()=>{if(!map)return;map.eachLayer(l=>{if(l instanceof L.CircleMarker)map.removeLayer(l)});visible.forEach(r=>{const color=r.status==="restored"?"#16a34a":r.status==="partial"?"#f59e0b":"#dc2626";const marker=L.circleMarker([r.lat,r.lng],{radius:9,fillColor:color,color:"#fff",weight:2,fillOpacity:.9});marker.bindPopup("<b>"+esc(r.service).toUpperCase()+"</b><br>"+esc(r.status)+"<br>Confidence: "+esc(r.confidence)+"%<br>"+esc(r.description||"No description")+"<br><small>Confirmations: "+esc(r.confirmations)+"</small>");marker.addTo(map)});if(loc)L.circleMarker(loc,{radius:7,color:"#155eef",fillColor:"#155eef",fillOpacity:1}).bindPopup("Your location").addTo(map)},[map,visible,loc]);
async function report(e){e.preventDefault();if(!loc){alert("Allow location access to report from your current area.");return}const res=await fetch(API+"/api/reports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({service:form.service,status:"down",lat:loc[0],lng:loc[1],description:form.description})});if(res.ok){setForm(x=>({...x,description:""}));}else alert("Could not submit the report. Please try again.")}
return <div className="app"><header><div className="brand"><div className="brandmark">L</div><div><strong>LiveCity</strong><span>See what's working. See what's not.</span></div></div><button onClick={()=>loc&&map?.setView(loc,14)}>📍 My location</button></header><aside><h1>Live essential services</h1><p className="muted">A live community signal for the things your city depends on.</p><div className="chips"><button className={service==="all"?"active":""} onClick={()=>setService("all")}>All</button>{services.map(s=><button key={s.id} className={service===s.id?"active":""} onClick={()=>setService(s.id)}>{s.icon} {s.label}</button>)}</div><section className="card"><h2>Report a problem</h2><form onSubmit={report}><select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}>{services.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="What is happening? (optional)"/><button className="primary">Report outage</button></form><div className="status-note">{online?"Live connection active.":"Live connection unavailable — showing the latest available data."}</div></section><section className="stats"><div><b>{visible.filter(r=>r.status!=="restored").length}</b><span>Active reports</span></div><div><b>{visible.filter(r=>r.confidence>=80).length}</b><span>High confidence</span></div></section><p className="foot">Community reports are signals, not official utility confirmations. Verify critical information with the relevant provider.</p></aside><main id="map"/></div>}
createRoot(document.getElementById("root")).render(<App/>);